<dependencies>
  <!-- Vert.x dependencies -->
  <dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-core</artifactId>
    <version>4.5.11</version>
  </dependency>
  <dependency>
    <groupId>io.vertx</groupId>
    <artifactId>vertx-web</artifactId>
    <version>4.5.11</version>
  </dependency>
  <!-- SLF4J logging -->
  <dependency>
<!--    <groupId>ch.qos.logback</groupId>-->
<!--    <artifactId>logback-classic</artifactId>-->
<!--    <version>${logback-classic.version}</version>-->
<!--  </dependency>-->
<!--  <dependency>-->
<!--    <groupId>org.apache.logging.log4j</groupId>-->
<!--    <artifactId>log4j-slf4j-impl</artifactId>-->
<!--    <version>2.12.4</version>-->
<!--  </dependency>-->

  <dependency>

    <dependency>
      <groupId>io.vertx</groupId>
      <artifactId>vertx-pg-client</artifactId>
    </dependency>
    <groupId>org.slf4j</groupId>
    <artifactId>slf4j-api</artifactId>
    <version>2.0.13</version>
  </dependency>
  <dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-classic</artifactId>
    <version>1.5.16</version>
  </dependency>
  <dependency>
    <groupId>ch.qos.logback</groupId>
    <artifactId>logback-core</artifactId>
    <version>1.5.16</version>
  </dependency>

</dependencies>
